name: Frontend Deploy

on:
  workflow_run:
    workflows: ["Frontend Test"]
    types:
      - completed
    branches:
      - setup
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Download the artifacts from the CI workflow
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Frontend Test
          workflow_conclusion: success
          name: next-build
          path: .

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Production Server
        run: |
          echo "🚀 Deploying .next build to server..."
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no -r .next package.json pnpm-lock.yaml \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/AI-Ad-Gen-Frontend"

      - name: Start Application on Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" << 'EOF'
            set -e  # Stop script on error
            cd /home/${{ secrets.SERVER_USER }}/AI-Ad-Gen-Frontend
            pnpm install --frozen-lockfile
            pm2 delete ai-adgen-frontend || true
            pm2 start pnpm --name ai-adgen-frontend -- start
          EOF